FROM ubuntu:20.04
ARG BINARYEN_VERSION=111
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
      wget && \
    wget https://github.com/WebAssembly/binaryen/releases/download/version_${BINARYEN_VERSION}/binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz && \
    tar -xf binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz --strip-components=1 -C /opt && \
    rm binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz
ENV PATH="$PATH:/opt/bin"
